spring.application.name=USER-REGISTER-SERVICE
server.port=7777

#Githun link for config server
spring.config.import=optional:configserver:http://localhost:6666

## Eureka Config
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true

## Force hostname to localhost
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
jwt.secret=3273357638792F423F4528SJCDNKLCMCMCKCDMOD655368566D597133743677397A244326


